- Media:
    - Jellyfin:
        href: http://192.168.1.152:8096
        description: Media Server
        icon: jellyfin.png
    - qBittorrent:
        href: http://192.168.1.152:8081
        description: Torrent client (VPN)
        icon: qbittorrent.png

- Management:
    - Portainer:
        href: http://192.168.1.152:9000
        description: Container Management
        icon: portainer.png
    - Uptime Kuma:
        href: http://192.168.1.152:3001
        description: Service Monitoring
        icon: uptime-kuma.png
    - Cockpit:
        href: https://192.168.1.152:9090
        description: System Management
        icon: cockpit.png

- Network:
    - Gluetun:
        href: http://192.168.1.152:8000
        description: VPN gateway (Proton CH)
        icon: gluetun.png
    - Pi-hole:
        href: http://192.168.1.152:8080/admin
        description: DNS & ad blocking
        icon: pi-hole.png

- System:
    - Scrutiny:
        href: http://192.168.1.152:8082
        description: Drive Health
        icon: scrutiny.png

- Home:
    - Home Assistant:
        href: http://192.168.1.124:8123
        description: Home Automation
        icon: home-assistant.png
