- Media:
    - Jellyfin:
        href: https://jellyfin.lennyhomelab.co.uk
        description: Media Server
        icon: jellyfin.png
    - qBittorrent:
        href: http://192.168.1.152:8081
        description: Torrent client (VPN)
        icon: qbittorrent.png

- Management:
    - Portainer:
        href: http://192.168.1.152:9000
        description: Container Management
        icon: portainer.png
    - Uptime Kuma:
        href: http://192.168.1.152:3001
        description: Service Monitoring
        icon: uptime-kuma.png
    - Scrutiny:
        href: http://192.168.1.152:8082/web/dashboard
        description: Drive health (SMART)
        icon: scrutiny.png
    - Cockpit:
        href: https://192.168.1.152:9090
        description: System Management
        icon: cockpit.png

- Network:
    - Gluetun:
        href: http://192.168.1.152:8000
        description: VPN gateway (Proton CH)
        icon: gluetun.png
    - Pi-hole:
        href: https://pihole.lennyhomelab.co.uk/admin
        description: DNS & ad blocking
        icon: pi-hole.png
